#%RAML 1.0 DocumentationItem
title: RAML API Template
content: |
    This is a generic API Template to serve as an accelerator for designing API specifications by providing - 
    - Ready to use ResourceTypes collections
    - Multiple API Authentication schemes
    - A uniform structure for API fault Responses
    - Customized Data-types and Examples for reference
    - Embedded description and documentation
    - RESTful best practices

    It forms a baseline for an API spec and has embedded modules for reusable fragments. 

    API Design Admins could customize the specification and associated modules based on Organizational requirements.

    API Designers just need to focus on -
    - API Resource hierarchy
    - Datatypes and Examples of Requests and Responses

    
    