#%RAML 1.0 DataType
type: object
description: Address datatype
additionalProperties: false
properties:
  street?: 
    type: string
    description: Street Name
  street2?: 
    type: string
    description: Street Landmark
  city?: 
    type: string
    description: City
  state?: 
    type: string
    description: State
  postalCode?: 
    type: string
    description: Postal Code
  country?: 
    type: string
    description: Country