#%RAML 1.0 Library
types:
  account: !include Account.raml
  address: !include Address.raml
  post-account-resp: !include responses/post-account-resp.raml
  put-account-resp: !include responses/put-account-resp.raml
  get-account-pages-resp: !include responses/get-account-paged-resp.raml