#%RAML 1.0 Trait
  description: Client Id Enforcement
  headers: 
    client_id:
      type: string
      description: API Client Id
    client_secret:
      type: string
      description: API Client Secret
