#%RAML 1.0 Trait
    responses:
      200:
        description: |
          Success
        body:
          application/json:
            type: <<responseType>>
            example: <<responseExample>>