#%RAML 1.0 Trait
    responses:
      201:
        description: |
          Created
        body:
          application/json:
            type: <<responseType>>
            example: <<responseExample>>