#%RAML 1.0 Trait
    responses:
      202:
        description: |
          Accepted
        body:
          application/json:
            type: <<responseType>>
            example: <<responseExample>>