#%RAML 1.0 DocumentationItem
title: 4xx Client Errors
content: The resource identified by the request is only capable of generating response entities which have content characteristics not acceptable according to the accept headers sent in the request.